PackageName: "ExpressionTreeForge"
PackageOwner: "JuliaSmoothOptimizers"
PackageUUID: "93090adf-0e31-445f-8c8f-44d91f61d7ad"
_src_path: "https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl"
_commit: "v0.13.0"
AddBreakage: true
AddBenchmark: false
AddBenchmarkCI: true
