PackageName: "ExpressionTreeForge"
PackageOwner: "JuliaSmoothOptimizers"
PackageUUID: "93090adf-0e31-445f-8c8f-44d91f61d7ad"
_src_path: "https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl"
_commit: "7bcc7d0a2905be7ca9d1dd6519e8df59ae89605c"
AddBreakage: true
AddBenchmark: false
AddBenchmarkCI: true
AddCirrusCI: true
